<div class="flash-sale-catalog">
<?php
/**
 * @var \Task\FlashSale\Block\FlashSale $block
 */
echo print_r($block->getConfigurableProduct(), true);
foreach ($block->flashSaleItems() as $value) {
    if ($value['sku'] == $block->getCurrentProduct()->getSku()) {
        if (isset($block->flashSaleDetails()[0]['flash_sale_name'])) {
            echo '<h2>Flash Sale : ' . $block->flashSaleDetails()[0]['flash_sale_name'] . " Ends In " . gmdate("H:i:s", $block->flashSaleRemainingTime()) . " </h2>";
        }
        echo "<h4>There is on-going Flash sale for this product</h4>";
        echo "<h4>Offer Price " . $block->getCurrentProduct()->getFinalPrice() . "</h4>";
        echo '<h4><i>Quantity Left: ' . $value['qty_left'] . '</i></h4><br>';
        if ($value['qty_left'] == 0) {
            echo "<b>No Stock Left</b><br>";
        }
        if ($value['qty_left'] <= 2  && $value['qty_left'] > 0) {
            echo "<h4><p class='qty-left'>only " . $value['qty_left'] . " left in " . $value['sku'] . "</p><br></h4>";
        }
    }
}

?>
</div>
