<?php
/**
 * @var \Task\FlashSale\Block\FlashSale $block
 */

foreach ($block->flashSaleItems() as $value) {
    if ($value['sku'] == $block->getCurrentProduct()->getSku() && $block->getCurrentProduct()->getTypeId() == 'simple' && $block->getCurrentProduct()->getTypeId() == 'grouped') {
        if (isset($block->flashSaleDetails()[0]['flash_sale_name'])) {
            echo '<div class="flash-sale-catalog"><h1><b>Flash Sale : ' . $block->flashSaleDetails()[0]['flash_sale_name'] . " Ends In " . gmdate("H:i:s", $block->flashSaleRemainingTime()) . " </b></h1>";
        }
        echo "<h4>There is on-going Flash sale for " . $value['sku'] . " product</h4>";
        echo "<h4>Offer Price : " . $block->getCurrentProduct()->getFinalPrice() . "</h4>";
        echo '<h4><i>Quantity Left : ' . $value['qty_left'] . '</i></h4><br>';
        if ($value['qty_left'] == 0) {
            echo "<b>No Stock Left</b><br>";
        }
        if ($value['qty_left'] <= 2  && $value['qty_left'] > 0) {
            echo "<h4><p class='qty-left'>only " . $value['qty_left'] . " left in " . $value['sku'] . "</p><br></h4></div>";
        }
    }
}

if ($block->getCurrentProduct()->getTypeId() == 'configurable') {
    if (isset($block->flashSaleDetails()[0]['flash_sale_name'])) {
        echo '<div class="flash-sale-catalog"><h2>Flash Sale : ' . $block->flashSaleDetails()[0]['flash_sale_name'] . " Ends In " . gmdate("H:i:s", $block->flashSaleRemainingTime()) . " </h2>";
    }
    foreach ($block->flashSaleItems() as $value) {
        foreach ($block->getConfigurableProduct() as $sku) {
            if ($value['sku'] == $sku['sku']) {
                echo "<h4>There is on-going Flash sale for " . $sku['sku'] . " product</h4>";
                echo "<h4>Offer Price : " . $sku['finalprice'] . "</h4>";
                echo '<h4><i>Quantity Left : ' . $value['qty_left'] . '</i></h4><br>';
                if ($value['qty_left'] == 0) {
                    echo "<b>No Stock Left</b><br>";
                }
                if ($value['qty_left'] <= 2  && $value['qty_left'] > 0) {
                    echo "<h4><p class='qty-left'>only " . $value['qty_left'] . " left in " . $value['sku'] . "</p><br></h4></div>";
                }
            }
        }
    }
}

if ($block->getCurrentProduct()->getTypeId() == 'grouped') {
    if (isset($block->flashSaleDetails()[0]['flash_sale_name'])) {
        echo '<div class="flash-sale-catalog"><h2>Flash Sale : ' . $block->flashSaleDetails()[0]['flash_sale_name'] . " Ends In " . gmdate("H:i:s", $block->flashSaleRemainingTime()) . " </h2>";
    }
    foreach ($block->flashSaleItems() as $value) {
        foreach ($block->getGroupedProduct() as $sku) {
            if ($value['sku'] == $sku['sku']) {
                echo "<h4>There is on-going Flash sale for " . $sku['sku'] . " product</h4>";
                echo "<h4>Offer Price : " . $sku['finalprice'] . "</h4>";
                echo '<h4><i>Quantity Left : ' . $value['qty_left'] . '</i></h4><br>';
                if ($value['qty_left'] == 0) {
                    echo "<b>No Stock Left</b><br>";
                }
                if ($value['qty_left'] <= 2  && $value['qty_left'] > 0) {
                    echo "<h4><p class='qty-left'>only " . $value['qty_left'] . " left in " . $value['sku'] . "</p><br></h4></div>";
                }
            }
        }
    }
}

if ($block->getCurrentProduct()->getTypeId() == 'bundle') {
    if (isset($block->flashSaleDetails()[0]['flash_sale_name'])) {
        echo '<div class="flash-sale-catalog"><h2>Flash Sale : ' . $block->flashSaleDetails()[0]['flash_sale_name'] . " Ends In " . gmdate("H:i:s", $block->flashSaleRemainingTime()) . " </h2>";
    }
    foreach ($block->flashSaleItems() as $value) {
        foreach ($block->getBundleProduct() as $sku) {
            if ($value['sku'] == $sku['sku']) {
                echo "<h4>There is on-going Flash sale for " . $sku['sku'] . " product</h4>";
                echo "<h4>Offer Price : " . $sku['finalprice'] . "</h4>";
                echo '<h4><i>Quantity Left : ' . $value['qty_left'] . '</i></h4><br>';
                if ($value['qty_left'] == 0) {
                    echo "<b>No Stock Left</b><br>";
                }
                if ($value['qty_left'] <= 2  && $value['qty_left'] > 0) {
                    echo "<h4><p class='qty-left'>only " . $value['qty_left'] . " left in " . $value['sku'] . "</p><br></h4></div>";
                }
            }
        }
    }
}
