<div class="flash-sale">

<?php

/**
 * @var \Trends\CustomBlock\Block\Display $block
 */
if (isset($block->flashSaleDetails()[0]['flash_sale_name'])) {
    echo ' <pre><h2>Flash Sale : ' . $block->flashSaleDetails()[0]['flash_sale_name'] . " Ends In " . gmdate("H:i:s", $block->flashSaleRemainingTime()) . " </h2>";
    echo '<div class="left">';
    foreach ($block->flashSaleItems() as $value) {
        echo '<h3><li><b>' . $value['sku'] . '</b></li></h3>';
    }
    echo '</div><div class = "right">';
    foreach ($block->flashSaleItems() as $value) {
        echo "<h3>" . $value['sku'] . " ";
        $max = $value['qty_left'] + $value['qty_ordered'];
        echo '<progress id="progress" value=' . $value['qty_left'] . ' max=' . $max . '>' . $value['qty_left'] . '</progress><br></h3>';
        echo '<i>Quantity Left: ' . $value['qty_left'] . '</i><br>';
        if ($value['qty_left'] == 0) {
            echo "<b>No Stock Left</b>";
        }
        if ($value['qty_left'] <= 2  && $value['qty_left'] > 0) {
            echo "<p class='qty-left'>only " . $value['qty_left'] . " left in " . $value['sku'] . "</p><br>";
        }
    }
}

 ?>
</div>
</div>
