<?php
namespace Trends\Custom\Controller\Page;

class Index extends \Magento\Framework\App\Action\Action
{
    protected $_postFactory;
    protected $_value;

    public function __construct(
        \Magento\Framework\App\Action\Context $context,
        \Trends\Custom\Model\PostFactory $postFactory,   //autogenerated file can be found in generated/code/Vendor/HelloWorld/Model/PostFactory.php
        \Trends\Custom\Model\Post $value
    ) {
        $this->_value = $value;
        $this->_postFactory = $postFactory;
        return parent::__construct($context);
    }

    public function execute()
    {
        $post = $this->_postFactory->create();
        $collection = $post->getCollection();
        foreach ($collection as $item) {
            echo "<pre>";
            print_r($item->getData());
            echo "</pre>";
        }

        echo $this->_value->getDefaultValues();
        $value = $this->_value->getIdentities();
        foreach ($value as $key => $value) {
            echo '<br>', $key, ' ', $value, '<br>';
        }
    }
}
