<?php
/** @var  \TrendsAttribute\Store\Block\Info $block*/

echo sprintf("Store Id : %s", $block->getStoreId()) . '<br />';
echo sprintf("Store Code : %s", $block->getStoreCode()) . '<br />';
echo sprintf("Store Website Id : %s", $block->getWebsiteId()) . '<br />';
echo sprintf("Store Name : %s", $block->getStoreName()) . '<br />';
echo sprintf("Store Store URL : %s", $block->getStoreUrl()) . '<br />';
echo sprintf("Store Active/Inactive : %s", $block->isStoreActive()) . '<br />';
